spring:

  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&sserverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    aop: #是否支持AOP
      auto: true


mybatis:
  mapper-locations: classpath:mapper/*.xml  #对应mapper映射xml文件所在路径
  type-aliases-package: com.example.chart.entity  #对应实体类路径
data:
  elasticsearch:
    cluster-nodes: localhost:9200
    cluster-name: elasticsearch
#分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true # 修改默认值，自动优化参数
