package com.example.chart.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SimsExam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMS_EXAM.EXAM_ID
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    private String examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMS_EXAM.C1
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    private String c1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMS_EXAM.STUDENT_ID
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMS_EXAM.EXAM_NAME
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    private String examName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMS_EXAM.EXAM_SCORE
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    private BigDecimal examScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMS_EXAM.TENANT_ID
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMS_EXAM.REVISION
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    private Integer revision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMS_EXAM.CREATED_BY
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMS_EXAM.CREATED_TIME
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMS_EXAM.UPDATED_BY
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMS_EXAM.UPDATED_TIME
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMS_EXAM.EXAM_ID
     *
     * @return the value of SIMS_EXAM.EXAM_ID
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public String getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMS_EXAM.EXAM_ID
     *
     * @param examId the value for SIMS_EXAM.EXAM_ID
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public void setExamId(String examId) {
        this.examId = examId == null ? null : examId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMS_EXAM.C1
     *
     * @return the value of SIMS_EXAM.C1
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public String getC1() {
        return c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMS_EXAM.C1
     *
     * @param c1 the value for SIMS_EXAM.C1
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public void setC1(String c1) {
        this.c1 = c1 == null ? null : c1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMS_EXAM.STUDENT_ID
     *
     * @return the value of SIMS_EXAM.STUDENT_ID
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMS_EXAM.STUDENT_ID
     *
     * @param studentId the value for SIMS_EXAM.STUDENT_ID
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMS_EXAM.EXAM_NAME
     *
     * @return the value of SIMS_EXAM.EXAM_NAME
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public String getExamName() {
        return examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMS_EXAM.EXAM_NAME
     *
     * @param examName the value for SIMS_EXAM.EXAM_NAME
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public void setExamName(String examName) {
        this.examName = examName == null ? null : examName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMS_EXAM.EXAM_SCORE
     *
     * @return the value of SIMS_EXAM.EXAM_SCORE
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public BigDecimal getExamScore() {
        return examScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMS_EXAM.EXAM_SCORE
     *
     * @param examScore the value for SIMS_EXAM.EXAM_SCORE
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public void setExamScore(BigDecimal examScore) {
        this.examScore = examScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMS_EXAM.TENANT_ID
     *
     * @return the value of SIMS_EXAM.TENANT_ID
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMS_EXAM.TENANT_ID
     *
     * @param tenantId the value for SIMS_EXAM.TENANT_ID
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMS_EXAM.REVISION
     *
     * @return the value of SIMS_EXAM.REVISION
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public Integer getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMS_EXAM.REVISION
     *
     * @param revision the value for SIMS_EXAM.REVISION
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public void setRevision(Integer revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMS_EXAM.CREATED_BY
     *
     * @return the value of SIMS_EXAM.CREATED_BY
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMS_EXAM.CREATED_BY
     *
     * @param createdBy the value for SIMS_EXAM.CREATED_BY
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMS_EXAM.CREATED_TIME
     *
     * @return the value of SIMS_EXAM.CREATED_TIME
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMS_EXAM.CREATED_TIME
     *
     * @param createdTime the value for SIMS_EXAM.CREATED_TIME
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMS_EXAM.UPDATED_BY
     *
     * @return the value of SIMS_EXAM.UPDATED_BY
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMS_EXAM.UPDATED_BY
     *
     * @param updatedBy the value for SIMS_EXAM.UPDATED_BY
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMS_EXAM.UPDATED_TIME
     *
     * @return the value of SIMS_EXAM.UPDATED_TIME
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMS_EXAM.UPDATED_TIME
     *
     * @param updatedTime the value for SIMS_EXAM.UPDATED_TIME
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}