package com.example.chart.entity;

import java.util.Date;

public class SimsClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.CLASS_ID
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.COLLEGE_ID
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private String collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.MAJOR_ID
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private String majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.CLASS_NAME
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.STUDENT_NUMBER
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private Integer studentNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.ADVISER
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private String adviser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.ESTAB_DATE
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private Date estabDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.YEAR_NUMBER
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private Integer yearNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.TENANT_ID
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.REVISION
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private Integer revision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.CREATED_BY
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.CREATED_TIME
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.UPDATED_BY
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.UPDATED_TIME
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.CLASS_ID
     *
     * @return the value of sims_class.CLASS_ID
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.CLASS_ID
     *
     * @param classId the value for sims_class.CLASS_ID
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.COLLEGE_ID
     *
     * @return the value of sims_class.COLLEGE_ID
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public String getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.COLLEGE_ID
     *
     * @param collegeId the value for sims_class.COLLEGE_ID
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setCollegeId(String collegeId) {
        this.collegeId = collegeId == null ? null : collegeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.MAJOR_ID
     *
     * @return the value of sims_class.MAJOR_ID
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public String getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.MAJOR_ID
     *
     * @param majorId the value for sims_class.MAJOR_ID
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId == null ? null : majorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.CLASS_NAME
     *
     * @return the value of sims_class.CLASS_NAME
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.CLASS_NAME
     *
     * @param className the value for sims_class.CLASS_NAME
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.STUDENT_NUMBER
     *
     * @return the value of sims_class.STUDENT_NUMBER
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public Integer getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.STUDENT_NUMBER
     *
     * @param studentNumber the value for sims_class.STUDENT_NUMBER
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setStudentNumber(Integer studentNumber) {
        this.studentNumber = studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.ADVISER
     *
     * @return the value of sims_class.ADVISER
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public String getAdviser() {
        return adviser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.ADVISER
     *
     * @param adviser the value for sims_class.ADVISER
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setAdviser(String adviser) {
        this.adviser = adviser == null ? null : adviser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.ESTAB_DATE
     *
     * @return the value of sims_class.ESTAB_DATE
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public Date getEstabDate() {
        return estabDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.ESTAB_DATE
     *
     * @param estabDate the value for sims_class.ESTAB_DATE
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setEstabDate(Date estabDate) {
        this.estabDate = estabDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.YEAR_NUMBER
     *
     * @return the value of sims_class.YEAR_NUMBER
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public Integer getYearNumber() {
        return yearNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.YEAR_NUMBER
     *
     * @param yearNumber the value for sims_class.YEAR_NUMBER
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setYearNumber(Integer yearNumber) {
        this.yearNumber = yearNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.TENANT_ID
     *
     * @return the value of sims_class.TENANT_ID
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.TENANT_ID
     *
     * @param tenantId the value for sims_class.TENANT_ID
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.REVISION
     *
     * @return the value of sims_class.REVISION
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public Integer getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.REVISION
     *
     * @param revision the value for sims_class.REVISION
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setRevision(Integer revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.CREATED_BY
     *
     * @return the value of sims_class.CREATED_BY
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.CREATED_BY
     *
     * @param createdBy the value for sims_class.CREATED_BY
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.CREATED_TIME
     *
     * @return the value of sims_class.CREATED_TIME
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.CREATED_TIME
     *
     * @param createdTime the value for sims_class.CREATED_TIME
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.UPDATED_BY
     *
     * @return the value of sims_class.UPDATED_BY
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.UPDATED_BY
     *
     * @param updatedBy the value for sims_class.UPDATED_BY
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.UPDATED_TIME
     *
     * @return the value of sims_class.UPDATED_TIME
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.UPDATED_TIME
     *
     * @param updatedTime the value for sims_class.UPDATED_TIME
     *
     * @mbggenerated Wed Apr 26 16:49:42 CST 2023
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}