package com.example.chart.dao;

import com.example.chart.entity.SimsClass;
import com.example.chart.entity.SimsClassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SimsClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:17 CST 2023
     */
    int countByExample(SimsClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:17 CST 2023
     */
    int deleteByExample(SimsClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:17 CST 2023
     */
    int deleteByPrimaryKey(String examId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:17 CST 2023
     */
    int insert(SimsClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:17 CST 2023
     */
    int insertSelective(SimsClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:17 CST 2023
     */
    List<SimsClass> selectByExample(SimsClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:17 CST 2023
     */
    SimsClass selectByPrimaryKey(String examId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:17 CST 2023
     */
    int updateByExampleSelective(@Param("record") SimsClass record, @Param("example") SimsClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:17 CST 2023
     */
    int updateByExample(@Param("record") SimsClass record, @Param("example") SimsClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:17 CST 2023
     */
    int updateByPrimaryKeySelective(SimsClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:17 CST 2023
     */
    int updateByPrimaryKey(SimsClass record);
}