package com.example.chart.dao;

import com.example.chart.entity.SimsExam;
import com.example.chart.entity.SimsExamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SimsExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    int countByExample(SimsExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    int deleteByExample(SimsExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    int deleteByPrimaryKey(String examId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    int insert(SimsExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    int insertSelective(SimsExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    List<SimsExam> selectByExample(SimsExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    SimsExam selectByPrimaryKey(String examId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    int updateByExampleSelective(@Param("record") SimsExam record, @Param("example") SimsExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    int updateByExample(@Param("record") SimsExam record, @Param("example") SimsExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    int updateByPrimaryKeySelective(SimsExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMS_EXAM
     *
     * @mbggenerated Tue May 23 11:29:56 CST 2023
     */
    int updateByPrimaryKey(SimsExam record);
}